variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

test:
  stage: test
  image: node:14.4.0
  services:
    - docker:dind
    - node:14.4.0
  script:
    # Install protocol buffers.
    - PROTOC_ZIP=protoc-3.11.4-linux-x86_64.zip
    - curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v3.11.4/$PROTOC_ZIP
    - unzip -o $PROTOC_ZIP -d /usr/local bin/protoc
    - unzip -o $PROTOC_ZIP -d /usr/local 'include/*'
    - rm -f $PROTOC_ZIP
    # Install submodules.
    - git submodule update --init --recursive
    # Install dependencies.
    - npm install
    # Generate protobuf code.
    - npm run build-proto-linux
    - npm run build-grpc-linux
    # Check for Typescript type errors.
    - npm run check-typescript-types
    # Run tests.
    - npm test

lint:
  stage: test
  image: node:14.4.0
  services:
    - docker:dind
    - node:14.4.0
  script:
    - npm install
    - npm run lint

deploy:
  stage: deploy
  image: docker:stable
  services:
  - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
