variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

test:
  stage: test
  image: node:carbon
  services:
    - docker:dind
    - node:carbon
  script:
    - npm install
    - npm test

lint:
  stage: test
  image: node:carbon
  services:
    - docker:dind
    - node:carbon
  script:
    - npm install
    - npm run lint

deploy:
  stage: deploy
  image: docker:stable
  services:
  - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
