# image: node:carbon

# services:
#   - docker:dind

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
   image: docker:stable
   services:
    - docker:dind
   stage: build
    script:
      - docker build -t $IMAGE_TAG .

test:
  stage: test
  script: npm test

deploy:
  stage: deploy
  image: node:carbon
  script:
    - docker push $IMAGE_TAG
