variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker build -t $IMAGE_TAG .

test:
  stage: test
  image: node:carbon
  script: npm test

deploy:
  stage: deploy
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker push $IMAGE_TAG
