name: CI

on: [push]

jobs:
  build:
    container: golang:latest
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Node.js Setup
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      - name: Install Protocol buffers
        run: |
          PROTOC_ZIP=protoc-3.11.4-linux-x86_64.zip
          curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v3.11.4/$PROTOC_ZIP
          unzip -o $PROTOC_ZIP -d /usr/local bin/protoc
          unzip -o $PROTOC_ZIP -d /usr/local 'include/*'
          rm -f $PROTOC_ZIP
      - name: Build
        run: |
          npm ci
          npm run generate-stubs
          npm run check-typescript-types
          npm test
