name: CI

on: [push]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    container: golang:latest
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Node.js Setup
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      - name: Build
        run: |
          npm ci
          npm run generate-stubs
          npm run check-typescript-types
          npm test
