name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Node.js Setup
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.x'
      - name: Build
        run: |
          npm ci
          npm run generate-stubs
          npm run check-typescript-types
          npm test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: exit 0
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Deploy to K8s
        run: exit 0
